edit/delete project
SELab-2/OSOC-5 pull request #332
Opened 2022-05-04 11:14 UTC by lasaeren

closes #311
closes #229

2022-05-04 11:17 UTC, lasaeren commented
Current status
![image](https://user-images.githubusercontent.com/99676075/166671488-4cf2b1ce-dfd7-4571-a8df-7539b974a41d.png)

2022-05-04 11:38 UTC, lasaeren commented
Now loads the correct fields and selects the right coaches and skills
![image](https://user-images.githubusercontent.com/99676075/166673994-673929d0-dd43-41ef-972b-a60194d64f03.png)

2022-05-04 11:57 UTC, lasaeren commented
TODO's:
- [ ] Update, make a request with the new data
- [ ] Delete project, #229 for how to do this

2022-05-04 17:14 UTC, lasaeren commented
only thing left is doing the Update request to the server

2022-05-04 17:38 UTC, lasaeren commented
all done

2022-05-04 17:44 UTC, lasaeren commented
also fixed the merge conflicts, everything should still work 😓

2022-05-04 20:14 UTC, Zelzahn requested changes
Some `console.log()`'s are present, but otherwise very nicely done!

2022-05-04 20:14 UTC, Zelzahn commented on fe/src/features/projects/EditProject.vue
> +      console.log('updateProject')
🚨 The `console.log()` police is here 🚨

2022-05-04 20:14 UTC, Zelzahn commented on fe/src/features/projects/EditProject.vue
> +    updateProject() {
Is it possible to provide some documentation to the functions? Such that we don't need to retroactively add it in the `fe/documenation` branch.

2022-05-04 20:14 UTC, Zelzahn commented on fe/src/stores/useProjectStore.ts
> +          console.log(error)
👮‍♀️ Hands in the air!

2022-05-04 20:14 UTC, Zelzahn commented on fe/src/stores/useProjectStore.ts
> +        console.log(data)
You have the right to remain silent, everything you `console.log()` can and will be used against you. 🚨

2022-05-04 20:14 UTC, Zelzahn commented on fe/src/stores/useProjectStore.ts
> +      console.log('DELETED ' + id)
`console.log()` police, open up!

2022-05-04 20:14 UTC, Zelzahn commented on fe/src/stores/useProjectStore.ts
> +          console.log(error)
Sorry, I'm out of inspiration.

2022-05-04 21:18 UTC, Wouter01 requested changes

2022-05-04 21:18 UTC, Wouter01 commented on fe/src/features/projects/components/ProjectCard.vue
> +      router.push('/projects/' + this.project.id)
Please use the `to` attribute from a button instead of this function, e.g. ```:to="`/projects/${project.id}`"```

2022-05-04 21:18 UTC, Wouter01 commented on fe/src/features/projects/EditProject.vue
> +                glow-color="#00F1AF"
Remove or change the glow-color here, the green clashes with the red

2022-05-04 21:18 UTC, Wouter01 commented on fe/src/features/projects/EditProject.vue
> +                glow-color="#00F1AF"
Remove or change the glow-color here, the green clashes with the orange

2022-05-04 21:20 UTC, Wouter01 commented
I noticed the skills table is cut off when the screen is a bit smaller, while there are still large margins on the side. This seems like a waste of space, could you fix this? This also happens in create project.
![afbeelding](https://user-images.githubusercontent.com/62355975/166827666-3fde55fb-a97d-4300-ba58-4c99e3ad778a.png)

2022-05-05 07:26 UTC, lasaeren commented
> I noticed the skills table is cut off when the screen is a bit smaller, while there are still large margins on the side. This seems like a waste of space, could you fix this? This also happens in create project. ![afbeelding](https://user-images.githubusercontent.com/62355975/166827666-3fde55fb-a97d-4300-ba58-4c99e3ad778a.png)

@Wouter01 Redid the formatting a bit, it will now faster go under the first two boxes to give it more space, but long comments are still going to add a horizontal scrollbar

2022-05-05 09:26 UTC, lasaeren commented
fixed some bugs & also added an edit button for skills

2022-05-05 11:04 UTC, Zelzahn requested changes

2022-05-05 11:04 UTC, Zelzahn commented on fe/src/stores/useSkillStore.ts
> +      console.log(`Adding new skill: ${this.popupName}.`)
🚨 Woop woop 🚨

2022-05-05 11:04 UTC, Zelzahn commented on fe/src/stores/useSkillStore.ts
> +              console.log(response['data'])
👮‍♀️ Hold up those hands!

2022-05-05 11:04 UTC, Zelzahn commented on fe/src/stores/useSkillStore.ts
> +              console.log(error)
👀

2022-05-05 13:38 UTC, lasaeren commented on fe/src/stores/useCoachStore.ts
> +      const { results } = (await instance.get<{results: UserInterface[]}>('coaches/?page_size=500')).data
is temporary

2022-05-06 10:21 UTC, Zelzahn approved these changes

2022-05-06 10:21 UTC, merged