Create user feedback
SELab-2/OSOC-5 pull request #450
Opened 2022-05-18 09:13 UTC by lasaeren

- Added own email checker so email input is checked before actually sending it to the server
- notifications are now more clear and use feedback of the server
- popup stays open until all fields are valid or when "cancel" button is pressed

fixes #390

2022-05-19 09:35 UTC, Zelzahn approved these changes

2022-05-20 15:42 UTC, Wouter01 commented on fe/src/features/users/AddUser.vue
> -            (val) => (val.length >= 8) || 'Passwords must be longer then 7 characters',
`Password must have at least 8 characters` seems more natural language.

2022-05-20 15:42 UTC, Wouter01 commented on fe/src/features/users/AddUser.vue
>        color="yellow"
`password.length <= 8` should be `< 8`

2022-05-20 15:44 UTC, Wouter01 requested changes
See above comments

2022-05-21 06:56 UTC, merged